//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toptal.BikeRentals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toptal.BikeRentals.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Invalid credentials.&lt;/b&gt; No user can be found with the specified username and password. Please, try again..
        /// </summary>
        public static string Account_InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("Account_InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Locked out.&lt;/b&gt; The specified account has been locked out. Please, contact the Administrator..
        /// </summary>
        public static string Account_LockedOut {
            get {
                return ResourceManager.GetString("Account_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Unconfirmed account.&lt;/b&gt;The specified account has to be confirmed.  A confimation e-mail has been already sent. Please, check your inbox..
        /// </summary>
        public static string Account_RequiresVertification {
            get {
                return ResourceManager.GetString("Account_RequiresVertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Expected configuration setting &apos;{0}&apos; was not found in Application Settings.&lt;/b&gt; Please, contact the Administrator..
        /// </summary>
        public static string Configuration_AppSettingNotFound {
            get {
                return ResourceManager.GetString("Configuration_AppSettingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Transaction required for the operation was not found.&lt;/b&gt; Please, contact the Administrator. (Service: {0}, Operation: {1}).
        /// </summary>
        public static string DataAccess_TransactionRequiredForOperation {
            get {
                return ResourceManager.GetString("DataAccess_TransactionRequiredForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Entity not found.&lt;/b&gt; The requested entity was not found. (Entity: {1}, Key: {2}, Resource: {0}).
        /// </summary>
        public static string Entity_EntityNotFound {
            get {
                return ResourceManager.GetString("Entity_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Key error.&lt;/b&gt; The specified entity key is invalid. (Entity: {1}, Key: {2}, Resource: {0}).
        /// </summary>
        public static string Entity_InvalidKey {
            get {
                return ResourceManager.GetString("Entity_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Too much data.&lt;/b&gt; Too much data would be returned. Please, specify a filter.  (Entity: {1}, Required filter: {2}, Resource: {0}).
        /// </summary>
        public static string Entity_TooMuchDataFilterRequited {
            get {
                return ResourceManager.GetString("Entity_TooMuchDataFilterRequited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Unspecified error.&lt;/b&gt; Unfortunatelly, an error has occured during processing your request. Please, contact the Administrator. ({0}).
        /// </summary>
        public static string Error_GenericServerError {
            get {
                return ResourceManager.GetString("Error_GenericServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Invalid e-mail address.&lt;/b&gt; The selected e-mail address is already used. Please, enter a different address..
        /// </summary>
        public static string Register_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Register_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Unauthenticated.&lt;/b&gt; You have to log in to access the requested resource. (Permission: {1}, Resource: {0}).
        /// </summary>
        public static string Security_Unauthenticated {
            get {
                return ResourceManager.GetString("Security_Unauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Unauthorized.&lt;/b&gt; You don&apos;t have access to the requested resource. Please, contact the Administrator. (Permission: {1}, Resource: {0}).
        /// </summary>
        public static string Security_Unauthorized {
            get {
                return ResourceManager.GetString("Security_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Application startup error.&lt;/b&gt; One or more errors occured during the startup of the application. Please, contact the Administrator..
        /// </summary>
        public static string Startup_ErrorsOccured {
            get {
                return ResourceManager.GetString("Startup_ErrorsOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Input validation failed.&lt;/b&gt; Please, correct the following errors:|{0}.
        /// </summary>
        public static string Validation_Error {
            get {
                return ResourceManager.GetString("Validation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Incorrect data.&lt;/b&gt; Token validation failed. Please, reload the page..
        /// </summary>
        public static string Validation_InvalidAntiForgeryToken {
            get {
                return ResourceManager.GetString("Validation_InvalidAntiForgeryToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;One or more query parameters are invalid or missing.&lt;/b&gt; Please, contact the Administrator. (Parameter: {0}, Value: {1}).
        /// </summary>
        public static string Validation_InvalidOrMissingQueryParameters {
            get {
                return ResourceManager.GetString("Validation_InvalidOrMissingQueryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;One or more mandatory fields are missing.&lt;/b&gt; Please, fill all mandatory fields before proceeding!.
        /// </summary>
        public static string Validation_MandatoryFieldsAreMissing {
            get {
                return ResourceManager.GetString("Validation_MandatoryFieldsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Missing data.&lt;/b&gt; Expected input data was missing. Please, provide correct input. (Data: {1}, Resource: {0}).
        /// </summary>
        public static string Validation_MissingInputData {
            get {
                return ResourceManager.GetString("Validation_MissingInputData", resourceCulture);
            }
        }
    }
}
